export const en = {
    lang: 'en',
    employees: "Employees",
    add_new: "Add New",
    employee_list: "Employee List",
    first_name: "First Name",
    last_name: "Last Name",
    date_of_employment: "Date of Employment",
    date_of_birth: "Date of Birth",
    phone: "Phone",
    email: "Email",
    department: "Department",
    position: "Position",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    back: "Back",
    please_select: "Please Select",
    are_you_sure: "Are you sure?",
    delete_message: "Selected Employee record will be deleted!",
    proceed: "Proceed",
    first_name_error: "First Name is required",
    last_name_error: "Last Name is required",
    date_of_employment_error: "Date of Employment is required",
    date_of_birth_error: "Date of Birth is required",
    phone_error: "Please re-enter the phone number in the specified format.",
    email_error: "Email address is not valid",
    department_error: "Department is required",
    position_error: "Position is required"
};