export const tr = {
    employees: "Çalışanlar",
    add_new: "Yeni Ekle",
    employee_list: "Çalışan Listesi",
    first_name: "Ad",
    last_name: "Soyad",
    date_of_employment: "İşe Giriş Tarihi",
    date_of_birth: "Doğum Tarihi",
    phone: "Telefon",
    email: "E-Posta",
    department: "Departman",
    position: "Pozisyon",
    actions: "Eylemler",
    save: "Kaydet",
    cancel: "Vazgeç",
    edit: "Düzenle",
    delete: "Sil",
    back: "Geri Dön",
    please_select: "Seçiniz",
    are_you_sure: "Emin misiniz?",
    delete_message: "Seçilen çalışan kaydı silinecek!",
    proceed: "İlerle",
    first_name_error: "Ad alanı zorunludur",
    last_name_error: "Soyad alanı zorunludur",
    date_of_employment_error: "İşe Giriş Tarihi zorunludur",
    date_of_birth_error: "Doğum Tarihi zorunludur",
    phone_error: "Telefon numarasını belirtilen formata uygun şekilde tekrar giriniz",
    email_error: "Email adresinizi kontrol ediniz",
    department_error: "Departman seçimi zorunludur",
    position_error: "Pozisyon seçimi zorunludur"
};