export const members = [
    {
        id: 1,
        first_name: "Ahmet",
        last_name: "Sourtimes",
        date_of_employment: "2022-09-23",
        date_of_birth: "1990-03-15",
        phone: "+90 (555) 444 33 22",
        email: "ahmet@sourtimes.org",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 2,
        first_name: "Zeynep",
        last_name: "Kaya",
        date_of_employment: "2023-01-15",
        date_of_birth: "1988-07-08",
        phone: "+90 (555) 123 45 67",
        email: "zeynep@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 3,
        first_name: "Mehmet",
        last_name: "Özkan",
        date_of_employment: "2021-03-10",
        date_of_birth: "1992-11-22",
        phone: "+90 (555) 987 65 43",
        email: "mehmet@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 4,
        first_name: "Ayşe",
        last_name: "Demir",
        date_of_employment: "2023-06-05",
        date_of_birth: "1995-12-03",
        phone: "+90 (555) 246 81 35",
        email: "ayse@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 5,
        first_name: "Can",
        last_name: "Yılmaz",
        date_of_employment: "2020-08-12",
        date_of_birth: "1987-05-17",
        phone: "+90 (555) 369 14 72",
        email: "can@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 6,
        first_name: "Elif",
        last_name: "Şahin",
        date_of_employment: "2022-02-28",
        date_of_birth: "1991-09-29",
        phone: "+90 (555) 147 25 83",
        email: "elif@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 7,
        first_name: "Burak",
        last_name: "Arslan",
        date_of_employment: "2023-07-14",
        date_of_birth: "1994-01-11",
        phone: "+90 (555) 582 39 61",
        email: "burak@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 8,
        first_name: "Selin",
        last_name: "Koç",
        date_of_employment: "2021-11-03",
        date_of_birth: "1989-08-26",
        phone: "+90 (555) 714 96 28",
        email: "selin@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 9,
        first_name: "Emre",
        last_name: "Çelik",
        date_of_employment: "2022-04-19",
        date_of_birth: "1993-06-04",
        phone: "+90 (555) 853 17 42",
        email: "emre@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 10,
        first_name: "Deniz",
        last_name: "Aydın",
        date_of_employment: "2023-09-07",
        date_of_birth: "1996-02-13",
        phone: "+90 (555) 492 68 15",
        email: "deniz@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 11,
        first_name: "Oğuz",
        last_name: "Kılıç",
        date_of_employment: "2020-12-22",
        date_of_birth: "1986-10-18",
        phone: "+90 (555) 631 74 29",
        email: "oguz@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 12,
        first_name: "Pınar",
        last_name: "Doğan",
        date_of_employment: "2022-05-16",
        date_of_birth: "1990-04-07",
        phone: "+90 (555) 258 41 96",
        email: "pinar@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 13,
        first_name: "Kerem",
        last_name: "Güven",
        date_of_employment: "2023-01-30",
        date_of_birth: "1994-12-24",
        phone: "+90 (555) 867 52 31",
        email: "kerem@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 14,
        first_name: "Gamze",
        last_name: "Eren",
        date_of_employment: "2021-10-08",
        date_of_birth: "1988-07-16",
        phone: "+90 (555) 394 18 65",
        email: "gamze@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 15,
        first_name: "Murat",
        last_name: "Polat",
        date_of_employment: "2022-03-25",
        date_of_birth: "1992-11-09",
        phone: "+90 (555) 176 83 47",
        email: "murat@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 16,
        first_name: "İrem",
        last_name: "Öztürk",
        date_of_employment: "2023-08-11",
        date_of_birth: "1995-01-28",
        phone: "+90 (555) 529 64 18",
        email: "irem@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 17,
        first_name: "Serkan",
        last_name: "Aktaş",
        date_of_employment: "2020-06-04",
        date_of_birth: "1985-09-12",
        phone: "+90 (555) 748 36 92",
        email: "serkan@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 18,
        first_name: "Ceyda",
        last_name: "Karaca",
        date_of_employment: "2021-12-17",
        date_of_birth: "1991-03-05",
        phone: "+90 (555) 613 27 54",
        email: "ceyda@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 19,
        first_name: "Alper",
        last_name: "Çakır",
        date_of_employment: "2022-07-29",
        date_of_birth: "1993-05-19",
        phone: "+90 (555) 485 91 37",
        email: "alper@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 20,
        first_name: "Neslihan",
        last_name: "Bayrak",
        date_of_employment: "2023-11-13",
        date_of_birth: "1989-08-02",
        phone: "+90 (555) 372 15 68",
        email: "neslihan@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 21,
        first_name: "Volkan",
        last_name: "Şen",
        date_of_employment: "2021-04-06",
        date_of_birth: "1987-10-14",
        phone: "+90 (555) 926 48 13",
        email: "volkan@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 22,
        first_name: "Ece",
        last_name: "Yurt",
        date_of_employment: "2022-09-21",
        date_of_birth: "1994-06-27",
        phone: "+90 (555) 159 73 84",
        email: "ece@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 23,
        first_name: "Tolga",
        last_name: "Koşar",
        date_of_employment: "2020-02-09",
        date_of_birth: "1986-12-31",
        phone: "+90 (555) 684 29 51",
        email: "tolga@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 24,
        first_name: "Burcu",
        last_name: "Özer",
        date_of_employment: "2023-05-24",
        date_of_birth: "1992-04-20",
        phone: "+90 (555) 317 86 42",
        email: "burcu@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 25,
        first_name: "Hakan",
        last_name: "Bulut",
        date_of_employment: "2021-12-18",
        date_of_birth: "1990-11-06",
        phone: "+90 (555) 792 54 16",
        email: "hakan@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 26,
        first_name: "Tuğba",
        last_name: "Aslan",
        date_of_employment: "2022-08-02",
        date_of_birth: "1988-07-23",
        phone: "+90 (555) 465 12 78",
        email: "tugba@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 27,
        first_name: "Arda",
        last_name: "Tekin",
        date_of_employment: "2024-01-15",
        date_of_birth: "1995-02-10",
        phone: "+90 (555) 238 94 63",
        email: "arda@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 28,
        first_name: "Sibel",
        last_name: "Güler",
        date_of_employment: "2023-06-07",
        date_of_birth: "1991-09-17",
        phone: "+90 (555) 651 37 89",
        email: "sibel@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 29,
        first_name: "Bora",
        last_name: "Kayhan",
        date_of_employment: "2020-10-26",
        date_of_birth: "1987-01-04",
        phone: "+90 (555) 874 61 25",
        email: "bora@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 30,
        first_name: "Merve",
        last_name: "Çiftçi",
        date_of_employment: "2022-03-12",
        date_of_birth: "1993-05-29",
        phone: "+90 (555) 193 75 48",
        email: "merve@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 31,
        first_name: "Cenk",
        last_name: "Durmuş",
        date_of_employment: "2023-09-05",
        date_of_birth: "1994-08-15",
        phone: "+90 (555) 426 18 57",
        email: "cenk@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 32,
        first_name: "Gizem",
        last_name: "Ünal",
        date_of_employment: "2021-11-20",
        date_of_birth: "1989-12-08",
        phone: "+90 (555) 769 43 21",
        email: "gizem@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 33,
        first_name: "Onur",
        last_name: "Kara",
        date_of_birth: "1992-03-22",
        date_of_employment: "2022-04-14",
        phone: "+90 (555) 517 82 94",
        email: "onur@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 34,
        first_name: "Seda",
        last_name: "Mutlu",
        date_of_employment: "2023-07-01",
        date_of_birth: "1995-10-11",
        phone: "+90 (555) 358 26 74",
        email: "seda@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 35,
        first_name: "Fatih",
        last_name: "Erdoğan",
        date_of_employment: "2020-01-28",
        date_of_birth: "1985-06-07",
        phone: "+90 (555) 682 51 39",
        email: "fatih@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 36,
        first_name: "Cansu",
        last_name: "Çetin",
        date_of_employment: "2022-08-16",
        date_of_birth: "1990-04-03",
        phone: "+90 (555) 294 67 18",
        email: "cansu@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 37,
        first_name: "Barış",
        last_name: "Özkaya",
        date_of_employment: "2023-12-08",
        date_of_birth: "1993-11-25",
        phone: "+90 (555) 741 35 62",
        email: "baris@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 38,
        first_name: "Duygu",
        last_name: "Sezer",
        date_of_employment: "2021-05-23",
        date_of_birth: "1988-02-18",
        phone: "+90 (555) 536 94 17",
        email: "duygu@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 39,
        first_name: "Uğur",
        last_name: "Tuna",
        date_of_employment: "2022-10-10",
        date_of_birth: "1991-08-09",
        phone: "+90 (555) 813 72 45",
        email: "ugur@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 40,
        first_name: "Esra",
        last_name: "Bozkurt",
        date_of_employment: "2024-02-27",
        date_of_birth: "1994-07-14",
        phone: "+90 (555) 469 58 23",
        email: "esra@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 41,
        first_name: "Erdem",
        last_name: "Çakıroğlu",
        date_of_employment: "2020-07-11",
        date_of_birth: "1986-01-26",
        phone: "+90 (555) 627 14 86",
        email: "erdem@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 42,
        first_name: "Nazlı",
        last_name: "Yaman",
        date_of_employment: "2021-11-19",
        date_of_birth: "1989-09-12",
        phone: "+90 (555) 754 39 21",
        email: "nazli@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 43,
        first_name: "İlker",
        last_name: "Özdemir",
        date_of_employment: "2023-03-04",
        date_of_birth: "1992-05-30",
        phone: "+90 (555) 182 76 94",
        email: "ilker@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 44,
        first_name: "Begüm",
        last_name: "Akın",
        date_of_employment: "2022-06-17",
        date_of_birth: "1990-12-21",
        phone: "+90 (555) 495 63 17",
        email: "begum@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    },
    {
        id: 45,
        first_name: "Recep",
        last_name: "Işık",
        date_of_employment: "2021-09-09",
        date_of_birth: "1987-03-16",
        phone: "+90 (555) 318 85 42",
        email: "recep@company.com",
        department: "Analytics",
        position: "Medior",
        checked: false,
    },
    {
        id: 46,
        first_name: "Hilal",
        last_name: "Korkmaz",
        date_of_employment: "2023-12-25",
        date_of_birth: "1995-10-04",
        phone: "+90 (555) 671 47 29",
        email: "hilal@company.com",
        department: "Tech",
        position: "Junior",
        checked: false,
    },
    {
        id: 47,
        first_name: "Kaan",
        last_name: "Altın",
        date_of_employment: "2020-04-13",
        date_of_birth: "1984-07-27",
        phone: "+90 (555) 924 16 58",
        email: "kaan@company.com",
        department: "Analytics",
        position: "Senior",
        checked: false,
    },
    {
        id: 48,
        first_name: "Damla",
        last_name: "Kurt",
        date_of_employment: "2022-01-06",
        date_of_birth: "1991-11-13",
        phone: "+90 (555) 257 84 63",
        email: "damla@company.com",
        department: "Tech",
        position: "Medior",
        checked: false,
    },
    {
        id: 49,
        first_name: "Serhat",
        last_name: "Güneş",
        date_of_employment: "2023-08-22",
        date_of_birth: "1993-04-08",
        phone: "+90 (555) 746 92 15",
        email: "serhat@company.com",
        department: "Analytics",
        position: "Junior",
        checked: false,
    },
    {
        id: 50,
        first_name: "Yasemin",
        last_name: "Özkan",
        date_of_employment: "2021-05-14",
        date_of_birth: "1988-08-19",
        phone: "+90 (555) 583 71 34",
        email: "yasemin@company.com",
        department: "Tech",
        position: "Senior",
        checked: false,
    }
];